#!/bin/bash

HOTELPODS=(hotel-reserv-geo hotel-reserv-recommendation hotel-reserv-profile hotel-reserv-user hotel-reserv-search hotel-reserv-reservation-mmc hotel-reserv-rate hotel-reserv-reservation hotel-reserv-rate-mmc hotel-reserv-geo-mongo hotel-reserv-jaeger hotel-reserv-user-mongo hotel-reserv-profile-mmc consul hotel-reserv-reservation-mongo hotel-reserv-rate-mongo hotel-reserv-recommendation-mongo hotel-reserv-frontend hotel-reserv-profile-mongo)
REMAININGPODS=(local-path-provisioner coredns kindnet-cni kube-proxy etcd kube-apiserver kube-controller-manager kube-scheduler)

PODS=(${HOTELPODS[@]} ${REMAININGPODS[@]})


echo -e "pod,containerID,namespace,value" >> hotel_ns.csv

NS=(cgroup ipc mnt net pid uts)

for ns in ${NS[@]}
do
	nsvalue=$(ls -l /proc/1/ns/$ns | cut -d "[" -f 2 | cut -d "]" -f 1)
	echo "cluster,-,$ns,$nsvalue" >> hotel_ns.csv
done

for pod in ${PODS[@]}
do
	for container in $(crictl ps | grep $pod | awk '{print $1}')
	do
		for ns in ${NS[@]}
		do
			nspath="/proc/1/ns/$ns"
			nsvalue=$(crictl exec -i -t $container su | ls -l $nspath | cut -d "[" -f 2 | cut -d "]" -f 1)
			
			echo "$pod,$container,$ns,$nsvalue" >> hotel_ns.csv
		done

	done
done
